spring:
  application:
    name: Balance Tracker
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db
    username: balance
    password: b@lance
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
